import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';

test('brief, agent handoff, sample learning and repair work together',async()=>{
 const dom=new JSDOM('<div id="app"></div><div id="toast"></div>',{url:'http://localhost:4173/'});
 const {window}=dom;
 const globals=['window','document','location','localStorage','navigator','requestAnimationFrame'];
 const previous=new Map(globals.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));
 for(const k of ['window','document','location','localStorage','navigator'])Object.defineProperty(globalThis,k,{value:k==='window'?window:window[k],configurable:true,writable:true});
 globalThis.requestAnimationFrame=fn=>fn();
 window.scrollTo=()=>{};
 window.HTMLElement.prototype.scrollIntoView=()=>{};
 window.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
 window.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new window.Event('close'));};
 const errors=[];window.addEventListener('error',e=>errors.push(e.error));
 const click=s=>{const el=window.document.querySelector(s);assert.ok(el,`Missing ${s}`);el.click();};
 const tick=()=>new Promise(r=>setTimeout(r,15));
 const go=async hash=>{window.location.hash=hash;await tick();};
 const fill=(selector,value)=>{const el=window.document.querySelector(selector);assert.ok(el);el.value=value;el.dispatchEvent(new window.Event('input',{bubbles:true}));};
 try{
  await import('../public/app.js');
  assert.match(window.document.querySelector('h1').textContent,/Understand/);
  click('[data-action="new"]');await tick();
  assert.match(window.document.querySelector('.builder-sidebar>.eyebrow').textContent,/MVP/);
  const answers=['A booking app for coaches','Book a session in three minutes','Customers and coaches with separate permissions','Two weeks, mobile friendly, no payments','Browse coaches; Select slot; Book session; Show confirmation'];
  for(const answer of answers){fill('#answer',answer);click('[data-action="next"]');}
  assert.ok(window.document.querySelector('#output'));
  const edited='Edited MVP brief: add an email confirmation.';
  fill('#output',edited);click('[data-learn="pack"]');
  assert.ok(window.document.querySelector('.pack-dialog textarea').value.includes(edited));
  const changeSelect=(selector,value)=>{const el=window.document.querySelector(selector);assert.ok(el);el.value=value;el.dispatchEvent(new window.Event('change',{bubbles:true}));};
  const guided=window.document.querySelector('.pack-dialog textarea').value;
  changeSelect('#prompt-mode','concise');
  assert.ok(window.document.querySelector('.pack-dialog textarea').value.includes(edited));
  assert.ok(window.document.querySelector('.pack-dialog textarea').value.length<guided.length);
  changeSelect('#prompt-phase','change');
  fill('#prompt-change','Add a cancellation email');
  assert.match(window.document.querySelector('.pack-dialog textarea').value,/Add a cancellation email/);
  click('.pack-dialog .close');
  const saved=JSON.parse(window.localStorage.getItem('apexelerate.projects.v1'));
  assert.equal(saved[0].output,edited);assert.equal(saved[0].type,'mvp');
  await go('dashboard');assert.match(window.document.querySelector('.project-card p').textContent,/MVP build brief/);
  fill('#studio-search','nonexistent keyword');assert.equal(window.document.querySelectorAll('.project-card').length,0);
  click('[data-studio="clear"]');assert.equal(window.document.querySelectorAll('.project-card').length,1);
  changeSelect('#studio-type','sop');assert.equal(window.document.querySelectorAll('.project-card').length,0);
  click('[data-studio="clear"]');click('[data-view="list"]');assert.ok(window.document.querySelector('.project-list-view'));
  await go('project/'+saved[0].id);assert.equal(window.document.querySelector('#output').value,edited);
  await go('connect');assert.match(window.document.querySelector('.connection-card small').textContent,/does not access GitHub/);
  await go('learn');click('[data-concept="database"]');
  assert.match(window.document.querySelector('.source-header').textContent,/db\/schema.prisma/);
  click('[data-quiz="0"]');assert.match(window.document.querySelector('#quiz-feedback').textContent,/Not quite/);
  click('[data-quiz="2"]');assert.match(window.document.querySelector('#quiz-feedback').textContent,/Correct/);
  assert.deepEqual(JSON.parse(window.localStorage.getItem('apexelerate.learning.v1')),['database']);
  changeSelect('#lesson-status','done');assert.equal(window.document.querySelectorAll('#lesson-results button').length,1);
  fill('#lesson-search','no match');assert.match(window.document.querySelector('#lesson-results').textContent,/No matching/);
  click('[data-tutor-clear]');changeSelect('#tutor-level','advanced');changeSelect('#tutor-detail','deep');
  assert.ok(window.document.querySelector('.tutor-depth'));assert.ok(window.document.querySelector('[data-tquiz]'));
  changeSelect('#tutor-mode','quiz');assert.ok(window.document.querySelector('.quiz-focus'));
  changeSelect('#tutor-mode','walkthrough');assert.ok(!window.document.querySelector('.quiz-focus'));
  click('[data-learn-tab="ask"]');fill('#code-question','<img src=x onerror=alert(1)> hosting cost');
  window.document.querySelector('#ask-form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
  assert.match(window.document.querySelector('.chat-messages').textContent,/does not have an answer/);
  assert.equal(window.document.querySelector('.chat-question img'),null);
  click('[data-ask="Where is booking data stored?"]');assert.ok(window.document.querySelector('.chat-messages [data-concept="database"]'));
  click('[data-learn-tab="fix"]');fill('#problem','My logo looks blurry');
  window.document.querySelector('#diagnose-form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
  assert.ok(window.document.querySelector('.diagnosis-unknown'));
  click('[data-learn="sample-bug"]');assert.ok(window.document.querySelector('.diagnosis-result'));
  click('[data-learn="repair"]');assert.match(window.document.querySelector('.pack-dialog textarea').value,/concurrency test/);
  assert.deepEqual(errors,[]);
 }finally{clearTimeout(window.toastTimer);dom.window.close();for(const [k,descriptor]of previous){if(descriptor)Object.defineProperty(globalThis,k,descriptor);else delete globalThis[k];}}
});
